<?xml version="1.0"?>
<!DOCTYPE mame [
<!ELEMENT mame (game+)>
	<!ATTLIST mame build CDATA #IMPLIED>
	<!ELEMENT game (description, year?, manufacturer, history?, biosset*, rom*, disk*, sample*, chip*, video?, sound?, input?, dipswitch*, driver?)>
		<!ATTLIST game name CDATA #REQUIRED>
		<!ATTLIST game sourcefile CDATA #IMPLIED>
		<!ATTLIST game runnable (yes|no) "yes">
		<!ATTLIST game cloneof CDATA #IMPLIED>
		<!ATTLIST game romof CDATA #IMPLIED>
		<!ATTLIST game sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT history (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom md5 CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom dispose (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk md5 CDATA #IMPLIED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk merge CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
			<!ATTLIST disk status (baddump|nodump|good) "good">
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT video EMPTY>
			<!ATTLIST video screen (raster|vector) #REQUIRED>
			<!ATTLIST video orientation (vertical|horizontal) #REQUIRED>
			<!ATTLIST video width CDATA #IMPLIED>
			<!ATTLIST video height CDATA #IMPLIED>
			<!ATTLIST video aspectx CDATA #IMPLIED>
			<!ATTLIST video aspecty CDATA #IMPLIED>
			<!ATTLIST video refresh CDATA #REQUIRED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
		<!ELEMENT input EMPTY>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input control CDATA #IMPLIED>
			<!ATTLIST input buttons CDATA #IMPLIED>
			<!ATTLIST input coins CDATA #IMPLIED>
		<!ELEMENT dipswitch (dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ELEMENT dipvalue EMPTY>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver color (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver sound (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver graphic (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver protection (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver savestate (supported|unsupported) #REQUIRED>
			<!ATTLIST driver palettesize CDATA #REQUIRED>
]>

<mame build="0.106 (Jan  9 2023)">
	<game name="puckman" sourcefile="pacman.c">
		<description>PuckMan (Japan set 1, Probably Bootleg)</description>
		<year>1980</year>
		<manufacturer>Namco</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="32"/>
		<rom size="256"/>
		<rom size="256"/>
		<rom size="256"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="puckmana" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>PuckMan (Japan set 2)</description>
		<year>1980</year>
		<manufacturer>Namco</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="puckmanf" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>PuckMan (Japan set 1 with speedup hack)</description>
		<year>1980</year>
		<manufacturer>Namco</manufacturer>
		<rom size="4096"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="puckmanh" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Puckman (Falcom?)</description>
		<year>1980</year>
		<manufacturer>hack</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="pacman" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Pac-Man (Midway)</description>
		<year>1980</year>
		<manufacturer>[Namco] (Midway license)</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="pacmanf" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Pac-Man (Midway, with speedup hack)</description>
		<year>1980</year>
		<manufacturer>[Namco] (Midway license)</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="puckmod" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>PuckMan (Japan set 3)</description>
		<year>1981</year>
		<manufacturer>Namco</manufacturer>
		<rom size="4096"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="pacmod" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Pac-Man (Midway, harder)</description>
		<year>1981</year>
		<manufacturer>[Namco] (Midway license)</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="newpuc2" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Newpuc2</description>
		<year>1980</year>
		<manufacturer>hack</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="newpuc2b" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Newpuc2 (set 2)</description>
		<year>1980</year>
		<manufacturer>hack</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="newpuckx" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>New Puck-X</description>
		<year>1980</year>
		<manufacturer>hack</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="pacheart" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Pac-Man (Hearts)</description>
		<year>1981</year>
		<manufacturer>hack</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="hangly" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Hangly-Man (set 1)</description>
		<year>1981</year>
		<manufacturer>hack</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="hangly2" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Hangly-Man (set 2)</description>
		<year>1981</year>
		<manufacturer>hack</manufacturer>
		<rom size="4096"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="4096"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="4096"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="hangly3" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Hangly-Man (set 3)</description>
		<year>1981</year>
		<manufacturer>hack</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="piranhah" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Piranha (hack)</description>
		<year>1981</year>
		<manufacturer>hack</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="abscam" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Abscam</description>
		<year>1981</year>
		<manufacturer>GL (US Billiards License)</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="256"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="crush" sourcefile="pacman.c">
		<description>Crush Roller (Kural Samno)</description>
		<year>1981</year>
		<manufacturer>Kural Samno Electric</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="32"/>
		<rom size="256"/>
		<rom size="256"/>
		<rom size="256"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="crush2" sourcefile="pacman.c" cloneof="crush" romof="crush">
		<description>Crush Roller (Kural Esco - bootleg?)</description>
		<year>1981</year>
		<manufacturer>Kural Esco Electric</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="crush3" sourcefile="pacman.c" cloneof="crush" romof="crush">
		<description>Crush Roller (Kural - bootleg?)</description>
		<year>1981</year>
		<manufacturer>Kural Electric</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="crush4" sourcefile="pacman.c" cloneof="crush" romof="crush">
		<description>Crush Roller (Kural TWT)</description>
		<manufacturer>Kural TWT</manufacturer>
		<rom size="65536"/>
		<rom size="16384"/>
		<rom size="256"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="maketrax" sourcefile="pacman.c" cloneof="crush" romof="crush">
		<description>Make Trax (set 1)</description>
		<year>1981</year>
		<manufacturer>[Kural] (Williams license)</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="maketrxb" sourcefile="pacman.c" cloneof="crush" romof="crush">
		<description>Make Trax (set 2)</description>
		<year>1981</year>
		<manufacturer>[Kural] (Williams license)</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="korosuke" sourcefile="pacman.c" cloneof="crush" romof="crush">
		<description>Korosuke Roller</description>
		<year>1981</year>
		<manufacturer>Kural Electric</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="mbrush" sourcefile="pacman.c" cloneof="crush" romof="crush">
		<description>Magic Brush</description>
		<year>1981</year>
		<manufacturer>bootleg</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="paintrlr" sourcefile="pacman.c" cloneof="crush" romof="crush">
		<description>Paint Roller</description>
		<year>1981</year>
		<manufacturer>bootleg</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="pacplus" sourcefile="pacman.c">
		<description>Pac-Man Plus</description>
		<year>1982</year>
		<manufacturer>[Namco] (Midway license)</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="32"/>
		<rom size="256"/>
		<rom size="256"/>
		<rom size="256"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="joyman" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Joyman</description>
		<year>1982</year>
		<manufacturer>hack</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="ctrpllrp" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Caterpillar Pacman Hack</description>
		<year>1982</year>
		<manufacturer>hack</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="eyes" sourcefile="pacman.c">
		<description>Eyes (Digitrex Techstar)</description>
		<year>1982</year>
		<manufacturer>Digitrex Techstar (Rock-ola license)</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="32"/>
		<rom size="256"/>
		<rom size="256"/>
		<rom size="256"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="eyes2" sourcefile="pacman.c" cloneof="eyes" romof="eyes">
		<description>Eyes (Techstar)</description>
		<year>1982</year>
		<manufacturer>Techstar (Rock-ola license)</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="eyeszac" sourcefile="pacman.c" cloneof="eyes" romof="eyes">
		<description>Eyes (Zaccaria)</description>
		<year>1982</year>
		<manufacturer>Zaccaria / bootleg</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="mrtnt" sourcefile="pacman.c">
		<description>Mr. TNT</description>
		<year>1983</year>
		<manufacturer>Telko</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="32"/>
		<rom size="256"/>
		<rom size="256"/>
		<rom size="256"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="gorkans" sourcefile="pacman.c" cloneof="mrtnt" romof="mrtnt">
		<description>Gorkans</description>
		<year>1983</year>
		<manufacturer>Techstar</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="eggor" sourcefile="pacman.c">
		<description>Eggor</description>
		<year>1983</year>
		<manufacturer>Telko</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="32"/>
		<rom size="256"/>
		<rom size="256"/>
		<rom size="256"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="preliminary" emulation="good" color="preliminary" sound="imperfect" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="jumpshot" sourcefile="pacman.c">
		<description>Jump Shot</description>
		<year>1985</year>
		<manufacturer>Bally Midway</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="32"/>
		<rom size="256"/>
		<rom size="256"/>
		<rom size="256"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="jumpshtp" sourcefile="pacman.c" cloneof="jumpshot" romof="jumpshot">
		<description>Jump Shot Engineering Sample</description>
		<year>1985</year>
		<manufacturer>Bally Midway</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="shootbul" sourcefile="pacman.c">
		<description>Shoot the Bull</description>
		<year>1985</year>
		<manufacturer>Bally Midway</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="32"/>
		<rom size="256"/>
		<rom size="256"/>
		<rom size="256"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="piranha" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Piranha</description>
		<year>1981</year>
		<manufacturer>GL (US Billiards License)</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="256"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="piranhao" sourcefile="pacman.c" cloneof="puckman" romof="puckman">
		<description>Piranha (older)</description>
		<year>1981</year>
		<manufacturer>GL (US Billiards License)</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="256"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="nmouse" sourcefile="pacman.c">
		<description>Naughty Mouse (set 1)</description>
		<year>1981</year>
		<manufacturer>Amenip (Palcom Queen River)</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="32"/>
		<rom size="256"/>
		<rom size="256"/>
		<rom size="256"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="nmouseb" sourcefile="pacman.c" cloneof="nmouse" romof="nmouse">
		<description>Naughty Mouse (set 2)</description>
		<year>1981</year>
		<manufacturer>Amenip Nova Games Ltd.</manufacturer>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<rom size="2048"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="mspacman" sourcefile="pacman.c">
		<description>Ms. Pac-Man</description>
		<year>1981</year>
		<manufacturer>Midway</manufacturer>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="2048"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="4096"/>
		<rom size="32"/>
		<rom size="256"/>
		<rom size="256"/>
		<rom size="256"/>
		<video screen="raster" orientation="vertical" width="224" height="288" aspectx="3" aspecty="4" refresh="60.606060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="32"/>
	</game>
	<game name="mspacmnf" sourcefile="pacman.c" cloneof="mspacman" romof="mspacman">