<?xml version="1.0"?>
<!DOCTYPE mess [
<!ELEMENT mess (machine+)>
	<!ATTLIST mess build CDATA #IMPLIED>
	<!ELEMENT machine (description, year?, manufacturer, history?, biosset*, rom*, disk*, sample*, chip*, video?, sound?, input?, dipswitch*, driver?, device*, ramoption*)>
		<!ATTLIST machine name CDATA #REQUIRED>
		<!ATTLIST machine sourcefile CDATA #IMPLIED>
		<!ATTLIST machine runnable (yes|no) "yes">
		<!ATTLIST machine cloneof CDATA #IMPLIED>
		<!ATTLIST machine romof CDATA #IMPLIED>
		<!ATTLIST machine sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT history (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom md5 CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom dispose (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk md5 CDATA #IMPLIED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk merge CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
			<!ATTLIST disk status (baddump|nodump|good) "good">
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT video EMPTY>
			<!ATTLIST video screen (raster|vector) #REQUIRED>
			<!ATTLIST video orientation (vertical|horizontal) #REQUIRED>
			<!ATTLIST video width CDATA #IMPLIED>
			<!ATTLIST video height CDATA #IMPLIED>
			<!ATTLIST video aspectx CDATA #IMPLIED>
			<!ATTLIST video aspecty CDATA #IMPLIED>
			<!ATTLIST video refresh CDATA #REQUIRED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
		<!ELEMENT input EMPTY>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input control CDATA #IMPLIED>
			<!ATTLIST input buttons CDATA #IMPLIED>
			<!ATTLIST input coins CDATA #IMPLIED>
		<!ELEMENT dipswitch (dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ELEMENT dipvalue EMPTY>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver color (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver sound (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver graphic (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver protection (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver savestate (supported|unsupported) #REQUIRED>
			<!ATTLIST driver palettesize CDATA #REQUIRED>
		<!ELEMENT device (instance*, extension*)>
			<!ATTLIST device type CDATA #REQUIRED>
			<!ATTLIST device tag CDATA #IMPLIED>
			<!ATTLIST device mandatory CDATA #IMPLIED>
			<!ELEMENT instance EMPTY>
				<!ATTLIST instance name CDATA #REQUIRED>
				<!ATTLIST instance briefname CDATA #REQUIRED>
			<!ELEMENT extension EMPTY>
				<!ATTLIST extension name CDATA #REQUIRED>
		<!ELEMENT ramoption (#PCDATA)>
]>

<mess build="0.106 (Jan  9 2023)">
	<machine name="a2600" sourcefile="a2600.c">
		<description>Atari 2600 (NTSC)</description>
		<year>1977</year>
		<manufacturer>Atari</manufacturer>
		<video screen="raster" orientation="horizontal" width="160" height="226" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="128"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="bin"/>
			<extension name="a26"/>
		</device>
	</machine>
	<machine name="a5200" sourcefile="atari.c">
		<description>Atari 5200</description>
		<year>1982</year>
		<manufacturer>Atari</manufacturer>
		<rom size="2048"/>
		<video screen="raster" orientation="horizontal" width="336" height="225" aspectx="4" aspecty="3" refresh="59.923328"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="256"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="rom"/>
			<extension name="bin"/>
			<extension name="a52"/>
		</device>
	</machine>
	<machine name="a5200a" sourcefile="atari.c" cloneof="a5200" romof="a5200">
		<description>Atari 5200 (alt)</description>
		<year>1982</year>
		<manufacturer>Atari</manufacturer>
		<rom size="2048"/>
		<video screen="raster" orientation="horizontal" width="336" height="225" aspectx="4" aspecty="3" refresh="59.923328"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="256"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="rom"/>
			<extension name="bin"/>
			<extension name="a52"/>
		</device>
	</machine>
	<machine name="a7800" sourcefile="a7800.c">
		<description>Atari 7800 (NTSC)</description>
		<year>1986</year>
		<manufacturer>Atari</manufacturer>
		<rom size="4096"/>
		<video screen="raster" orientation="horizontal" width="320" height="225" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="256"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="a78"/>
		</device>
	</machine>
	<machine name="a7800p" sourcefile="a7800.c" cloneof="a7800" romof="a7800">
		<description>Atari 7800 (PAL)</description>
		<year>1986</year>
		<manufacturer>Atari</manufacturer>
		<rom size="16384"/>
		<video screen="raster" orientation="horizontal" width="320" height="226" aspectx="4" aspecty="3" refresh="50.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="256"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="a78"/>
		</device>
	</machine>
	<machine name="lynx" sourcefile="lynx.c">
		<description>Lynx</description>
		<year>1989</year>
		<manufacturer>Atari</manufacturer>
		<rom size="512"/>
		<video screen="raster" orientation="horizontal" width="160" height="102" aspectx="4" aspecty="3" refresh="30.000000"/>
		<driver status="preliminary" emulation="preliminary" color="good" sound="imperfect" graphic="good" savestate="unsupported" palettesize="4096"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="lnx"/>
		</device>
		<device type="quickload">
			<instance name="quickload" briefname="quik"/>
			<extension name="o"/>
		</device>
	</machine>
	<machine name="lynxa" sourcefile="lynx.c" cloneof="lynx" romof="lynx">
		<description>Lynx (alternate rom save!)</description>
		<year>1989</year>
		<manufacturer>Atari</manufacturer>
		<rom size="512"/>
		<video screen="raster" orientation="horizontal" width="160" height="102" aspectx="4" aspecty="3" refresh="30.000000"/>
		<driver status="preliminary" emulation="preliminary" color="good" sound="imperfect" graphic="good" savestate="unsupported" palettesize="4096"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="lnx"/>
		</device>
		<device type="quickload">
			<instance name="quickload" briefname="quik"/>
			<extension name="o"/>
		</device>
	</machine>
	<machine name="lynx2" sourcefile="lynx.c" cloneof="lynx" romof="lynx">
		<description>Lynx II</description>
		<year>1991</year>
		<manufacturer>Atari</manufacturer>
		<rom size="512"/>
		<video screen="raster" orientation="horizontal" width="160" height="102" aspectx="4" aspecty="3" refresh="30.000000"/>
		<driver status="preliminary" emulation="preliminary" color="good" sound="imperfect" graphic="good" savestate="unsupported" palettesize="4096"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="lnx"/>
		</device>
		<device type="quickload">
			<instance name="quickload" briefname="quik"/>
			<extension name="o"/>
		</device>
	</machine>
	<machine name="jaguar" sourcefile="jaguar.c">
		<description>Atari Jaguar</description>
		<year>1993</year>
		<manufacturer>Atari</manufacturer>
		<rom size="131072"/>
		<video screen="raster" orientation="horizontal" width="320" height="240" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="preliminary" emulation="good" color="good" sound="imperfect" graphic="imperfect" protection="preliminary" savestate="unsupported" palettesize="65534"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="jag"/>
			<extension name="abs"/>
			<extension name="bin"/>
			<extension name="rom"/>
		</device>
		<device type="quickload">
			<instance name="quickload" briefname="quik"/>
			<extension name="bin"/>
		</device>
	</machine>
	<machine name="nes" sourcefile="nes.c">
		<description>Nintendo Entertainment System (NTSC)</description>
		<year>1985</year>
		<manufacturer>Nintendo</manufacturer>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="59.940060"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="512"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="nes"/>
		</device>
	</machine>
	<machine name="nespal" sourcefile="nes.c" cloneof="nes" romof="nes">
		<description>Nintendo Entertainment System (PAL)</description>
		<year>1987</year>
		<manufacturer>Nintendo</manufacturer>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="50.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="512"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="nes"/>
		</device>
	</machine>
	<machine name="famicom" sourcefile="nes.c">
		<description>Famicom</description>
		<year>1983</year>
		<manufacturer>Nintendo</manufacturer>
		<rom size="8192"/>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="59.940060"/>
		<driver status="preliminary" emulation="preliminary" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="512"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="nes"/>
		</device>
		<device type="floppydisk">
			<instance name="floppydisk" briefname="flop"/>
			<extension name="dsk"/>
			<extension name="fds"/>
		</device>
	</machine>
	<machine name="famitwin" sourcefile="nes.c" cloneof="famicom" romof="famicom">
		<description>Famicom Twin</description>
		<year>1986</year>
		<manufacturer>Sharp</manufacturer>
		<rom size="8192"/>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="59.940060"/>
		<driver status="preliminary" emulation="preliminary" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="512"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="nes"/>
		</device>
		<device type="floppydisk">
			<instance name="floppydisk" briefname="flop"/>
			<extension name="dsk"/>
			<extension name="fds"/>
		</device>
	</machine>
	<machine name="gameboy" sourcefile="gb.c">
		<description>GameBoy</description>
		<year>1990</year>
		<manufacturer>Nintendo</manufacturer>
		<rom size="256"/>
		<video screen="raster" orientation="horizontal" width="160" height="144" aspectx="4" aspecty="3" refresh="59.732155"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="4"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="gb"/>
			<extension name="gmb"/>
			<extension name="cgb"/>
			<extension name="gbc"/>
			<extension name="sgb"/>
		</device>
	</machine>
	<machine name="supergb" sourcefile="gb.c">
		<description>Super GameBoy</description>
		<year>1994</year>
		<manufacturer>Nintendo</manufacturer>
		<video screen="raster" orientation="horizontal" width="256" height="224" aspectx="4" aspecty="3" refresh="59.732155"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="32768"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="gb"/>
			<extension name="gmb"/>
			<extension name="cgb"/>
			<extension name="gbc"/>
			<extension name="sgb"/>
		</device>
	</machine>
	<machine name="gbpocket" sourcefile="gb.c" cloneof="gameboy" romof="gameboy">
		<description>GameBoy Pocket</description>
		<year>1996</year>
		<manufacturer>Nintendo</manufacturer>
		<video screen="raster" orientation="horizontal" width="160" height="144" aspectx="4" aspecty="3" refresh="59.732155"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="4"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="gb"/>
			<extension name="gmb"/>
			<extension name="cgb"/>
			<extension name="gbc"/>
			<extension name="sgb"/>
		</device>
	</machine>
	<machine name="gbcolor" sourcefile="gb.c">
		<description>GameBoy Color</description>
		<year>1998</year>
		<manufacturer>Nintendo</manufacturer>
		<video screen="raster" orientation="horizontal" width="160" height="144" aspectx="4" aspecty="3" refresh="59.732155"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="32768"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="gb"/>
			<extension name="gmb"/>
			<extension name="cgb"/>
			<extension name="gbc"/>
			<extension name="sgb"/>
		</device>
	</machine>
	<machine name="snes" sourcefile="snes.c">
		<description>Super Nintendo Entertainment System (NTSC)</description>
		<year>1989</year>
		<manufacturer>Nintendo</manufacturer>
		<rom size="64"/>
		<rom size="2048"/>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="imperfect" emulation="good" color="good" sound="imperfect" graphic="imperfect" savestate="unsupported" palettesize="32768"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="smc"/>
			<extension name="sfc"/>
			<extension name="fig"/>
			<extension name="swc"/>
			<extension name="u1"/>
		</device>
	</machine>
	<machine name="snespal" sourcefile="snes.c" cloneof="snes" romof="snes">
		<description>Super Nintendo Entertainment System (PAL)</description>
		<year>1991</year>
		<manufacturer>Nintendo</manufacturer>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="50.000000"/>
		<driver status="imperfect" emulation="good" color="good" sound="imperfect" graphic="imperfect" savestate="unsupported" palettesize="32768"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="smc"/>
			<extension name="sfc"/>
			<extension name="fig"/>
			<extension name="swc"/>
			<extension name="u1"/>
		</device>
	</machine>
	<machine name="n64" sourcefile="n64.c">
		<description>Nintendo 64</description>
		<year>1996</year>
		<manufacturer>Nintendo</manufacturer>
		<video screen="raster" orientation="horizontal" width="640" height="480" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="4096"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="v64"/>
			<extension name="z64"/>
			<extension name="rom"/>
			<extension name="n64"/>
		</device>
	</machine>
	<machine name="megaduck" sourcefile="gb.c">
		<description>MegaDuck/Cougar Boy</description>
		<year>1993</year>
		<manufacturer>Creatronic/Videojet/Timlex/Cougar</manufacturer>
		<video screen="raster" orientation="horizontal" width="160" height="144" aspectx="4" aspecty="3" refresh="59.732155"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="4"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="bin"/>
		</device>
	</machine>
	<machine name="gamegear" sourcefile="sms.c">
		<description>Sega Game Gear (European/American)</description>
		<year>1990</year>
		<manufacturer>Sega</manufacturer>
		<rom bios="majesco" size="1024"/>
		<video screen="raster" orientation="horizontal" width="160" height="144" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="32"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="gg"/>
		</device>
	</machine>
	<machine name="sms" sourcefile="sms.c">
		<description>Sega Master System</description>
		<year>1986</year>
		<manufacturer>Sega</manufacturer>
		<rom bios="bios13" size="8192"/>
		<rom bios="hangonsh" size="262144"/>
		<rom bios="hangon" size="131072"/>
		<rom bios="alexkidd" size="131072"/>
		<rom size="131072"/>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="32"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="sms"/>
			<extension name="bin"/>
			<extension name="ic1"/>
		</device>
	</machine>
	<machine name="smspal" sourcefile="sms.c" cloneof="sms" romof="sms">
		<description>Sega Master System (PAL)</description>
		<year>1986</year>
		<manufacturer>Sega</manufacturer>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="50.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="32"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="sms"/>
			<extension name="bin"/>
			<extension name="ic1"/>
		</device>
	</machine>
	<machine name="smsj21" sourcefile="sms.c" cloneof="smsm3" romof="smsm3">
		<description>Samsung Gamboy</description>
		<year>1985</year>
		<manufacturer>Sega</manufacturer>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="32"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="sms"/>
			<extension name="bin"/>
			<extension name="ic1"/>
		</device>
	</machine>
	<machine name="smsm3" sourcefile="sms.c">
		<description>Sega Mark III</description>
		<year>1984</year>
		<manufacturer>Sega</manufacturer>
		<rom bios="jbios21" size="8192"/>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="32"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="sms"/>
			<extension name="bin"/>
			<extension name="ic1"/>
		</device>
	</machine>
	<machine name="gen_usa" sourcefile="genesis.c">
		<description>Genesis (USA, NTSC)</description>
		<year>1988</year>
		<manufacturer>Sega</manufacturer>
		<video screen="raster" orientation="horizontal" width="320" height="224" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="512"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="smd"/>
			<extension name="bin"/>
			<extension name="md"/>
			<extension name="ic1"/>
		</device>
	</machine>
	<machine name="gen_eur" sourcefile="genesis.c" cloneof="gen_usa" romof="gen_usa">
		<description>Megadrive (Europe, PAL)</description>
		<year>1988</year>
		<manufacturer>Sega</manufacturer>
		<video screen="raster" orientation="horizontal" width="320" height="240" aspectx="4" aspecty="3" refresh="50.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="512"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="smd"/>
			<extension name="bin"/>
			<extension name="md"/>
			<extension name="ic1"/>
		</device>
	</machine>
	<machine name="gen_jpn" sourcefile="genesis.c" cloneof="gen_usa" romof="gen_usa">
		<description>Megadrive (Japan, NTSC)</description>
		<year>1988</year>
		<manufacturer>Sega</manufacturer>
		<video screen="raster" orientation="horizontal" width="320" height="224" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="512"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="smd"/>
			<extension name="bin"/>
			<extension name="md"/>
			<extension name="ic1"/>
		</device>
	</machine>
	<machine name="astrocde" sourcefile="astrocde.c">
		<description>Bally Professional Arcade</description>
		<year>1978</year>
		<manufacturer>Bally Manufacturing</manufacturer>
		<rom size="8192"/>
		<video screen="raster" orientation="horizontal" width="320" height="204" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="256"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="bin"/>
		</device>
	</machine>
	<machine name="astrocdw" sourcefile="astrocde.c" cloneof="astrocde" romof="astrocde">
		<description>Bally Computer System</description>
		<year>1977</year>
		<manufacturer>Bally Manufacturing</manufacturer>
		<rom size="8192"/>
		<video screen="raster" orientation="horizontal" width="320" height="204" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="256"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="bin"/>
		</device>
	</machine>
	<machine name="vip" sourcefile="studio2.c">
		<description>COSMAC VIP</description>
		<year>1977</year>
		<manufacturer>RCA</manufacturer>
		<rom size="512"/>
		<rom size="512"/>
		<video screen="raster" orientation="horizontal" width="256" height="128" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="preliminary" emulation="preliminary" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="2"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="st2"/>
		</device>
	</machine>
	<machine name="studio2" sourcefile="studio2.c">
		<description>Studio II</description>
		<year>1976</year>
		<manufacturer>RCA</manufacturer>
		<rom size="2048"/>
		<video screen="raster" orientation="horizontal" width="256" height="128" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="2"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="st2"/>
		</device>
	</machine>
	<machine name="channelf" sourcefile="channelf.c">
		<description>Channel F</description>
		<year>1976</year>
		<manufacturer>Fairchild</manufacturer>
		<rom size="1024"/>
		<rom size="1024"/>
		<video screen="raster" orientation="horizontal" width="102" height="58" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="8"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="bin"/>
		</device>
	</machine>
	<machine name="coleco" sourcefile="coleco.c">
		<description>ColecoVision</description>
		<year>1982</year>
		<manufacturer>Coleco</manufacturer>
		<rom size="8192"/>
		<video screen="raster" orientation="horizontal" width="280" height="210" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="16"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="rom"/>
			<extension name="col"/>
			<extension name="bin"/>
		</device>
	</machine>
	<machine name="colecoa" sourcefile="coleco.c" cloneof="coleco" romof="coleco">
		<description>ColecoVision (Thick Characters)</description>
		<year>1982</year>
		<manufacturer>Coleco</manufacturer>
		<rom size="8192"/>
		<video screen="raster" orientation="horizontal" width="280" height="210" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="16"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="rom"/>
			<extension name="col"/>
			<extension name="bin"/>
		</device>
	</machine>
	<machine name="colecob" sourcefile="coleco.c" cloneof="coleco" romof="coleco">
		<description>SVI-603 Coleco Game Adapter</description>
		<year>1983</year>
		<manufacturer>Spectravideo</manufacturer>
		<rom size="8192"/>
		<video screen="raster" orientation="horizontal" width="280" height="210" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="16"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="rom"/>
			<extension name="col"/>
			<extension name="bin"/>
		</device>
	</machine>
	<machine name="adam" sourcefile="adam.c">
		<description>ColecoAdam</description>
		<year>1982</year>
		<manufacturer>Adam</manufacturer>
		<rom size="32768"/>
		<rom size="8192"/>
		<rom size="8192"/>
		<video screen="raster" orientation="horizontal" width="280" height="210" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="16"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="rom"/>
			<extension name="col"/>
			<extension name="bin"/>
		</device>
		<device type="floppydisk">
			<instance name="floppydisk1" briefname="flop1"/>
			<instance name="floppydisk2" briefname="flop2"/>
			<instance name="floppydisk3" briefname="flop3"/>
			<instance name="floppydisk4" briefname="flop4"/>
			<extension name="dsk"/>
		</device>
	</machine>
	<machine name="fnvision" sourcefile="fnvision.c">
		<description>FunVision</description>
		<year>1981</year>
		<manufacturer>Video Technology</manufacturer>
		<rom size="2048"/>
		<video screen="raster" orientation="horizontal" width="280" height="210" aspectx="4" aspecty="3" refresh="50.000000"/>
		<driver status="preliminary" emulation="preliminary" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="16"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="rom"/>
		</device>
	</machine>
	<machine name="pce" sourcefile="pce.c">
		<description>PC Engine</description>
		<year>1987</year>
		<manufacturer>Nippon Electronic Company</manufacturer>
		<video screen="raster" orientation="horizontal" width="360" height="256" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="imperfect" emulation="good" color="good" sound="imperfect" graphic="imperfect" savestate="unsupported" palettesize="512"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="pce"/>
		</device>
	</machine>
	<machine name="tg16" sourcefile="pce.c" cloneof="pce" romof="pce">
		<description>TurboGrafx 16</description>
		<year>1989</year>
		<manufacturer>Nippon Electronic Company</manufacturer>
		<video screen="raster" orientation="horizontal" width="360" height="256" aspectx="4" aspecty="3" refresh="60.000000"/>
		<driver status="imperfect" emulation="good" color="good" sound="imperfect" graphic="imperfect" savestate="unsupported" palettesize="512"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="pce"/>
		</device>
	</machine>
	<machine name="arcadia" sourcefile="arcadia.c">
		<description>Arcadia 2001</description>
		<year>1982</year>